### ISSUE TITLE
Images not Importing to WOA Site

### ISSUE THREAD

**Issue by LauraSeitter** [WaltersArtMuseum/api-thewalters-org#79] opened 2023-08-08 13:42 UTC
Hi all - I just noticed that the last two TMS imports I've done (dated 7/21 and 8/4) have not made it all the way to the works of art site. All the objects for which I've added new images now show up with "no image available" on the search results page, and when I open the record, none of the new images are present. Only previous images are there. 

Please let me know if I've done something wrong with the imports, and I'll be glad to try again. Also, I'm not sure if I put this on the correct thread, so please move if need be! Thanks in advance for your help.

**Comment by dylan-k** [comment] 2023-08-08 14:37
@LauraSeitter please share examples of accession numbers for artworks involved in each of the two imports. This will help us to test for data and images across the update path.

**Comment by dylan-k** [comment] 2023-08-08 14:38
Closing this, as the issue is not relevant to the API. As subject says, this is an art site issue. Moving the issue there.

**Closed by dylan-k** 2023-08-08 14:38 UTC
Labels: bug
